In [11]:
#Realizar o tratamento das bases coletadas via API do projeto final na aula 12

In [12]:
%pip install requests

Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (2023.11.17)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [13]:
import requests
import pandas as pd

from plyer import notification
from datetime import datetime

def alerta(code,tabela):
    
    HTTPcode = {200: "Sucesso", 201:"Created", 203:"Non Authoritative information", 204:"No Content", 
            400:"Bad request", 401: "Unauthorized", 403: "Forbidden", 404: "Not Found", 409: "Conflict",
            500: "Internal Server Error", 501: "Not Implemented", 502: "Bad Gateway", 503: "Service Unavailable", 504: "Gateway Timeout", 599: "Network timeout"
            }
    mensagem = HTTPcode.get(code)
    data = str(datetime.now()) 
    
    notification.notify(
        title= f"Código{code}",
        message = f"{mensagem} ao carregar {tabela}\n {data}",
        timeout=10
    )

In [14]:
#Escolher uma API da lista disponibel

url = "https://brasilapi.com.br/"

#Tabela 1

url1 = "https://brasilapi.com.br/api/banks/v1"
tabela1 = requests.get(url1)
code1 =tabela1.status_code

if code1 ==200: #code 200 é o código de sucesso
    data_json1 = tabela1.json() #se for sucesso, converte o conteúdo da resposta da solicitação HTTP (em formato JSON) para um objeto Python
else:
    alerta(code1,"Bank")

bank = pd.DataFrame(data_json1)
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ispb      359 non-null    object
 1   name      357 non-null    object
 2   code      348 non-null    float64
 3   fullName  357 non-null    object
dtypes: float64(1), object(3)
memory usage: 11.3+ KB

In [15]:
#Tabela 2
url2 = "https://brasilapi.com.br/api/pix/v1/participants"
tabela2 = requests.get(url2)
code2 =tabela2.status_code

if code2==200: #code 200 é o código de sucesso
    data_json2 = tabela2.json() #se for sucesso, converte o conteúdo da resposta da solicitação HTTP (em formato JSON) para um objeto Python
else:
   alerta(code2,"pix")

pix = pd.DataFrame(data_json2)
pix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 795 entries, 0 to 794
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ispb                     795 non-null    object
 1   nome                     795 non-null    object
 2   nome_reduzido            795 non-null    object
 3   modalidade_participacao  795 non-null    object
 4   tipo_participacao        795 non-null    object
 5   inicio_operacao          795 non-null    object
dtypes: object(6)
memory usage: 37.4+ KB

In [16]:
#Tabela 3 
url3 = "https://brasilapi.com.br/api/taxas/v1"
tabela3 = requests.get(url3)
code3 = tabela3.status_code

if code3 ==200: #code 200 é o código de sucesso
    data_json3 = tabela3.json() #se for sucesso, converte o conteúdo da resposta da solicitação HTTP (em formato JSON) para um objeto Python
else:
    alerta(code3,"Taxas")

tax = pd.DataFrame(data_json3) 
tax

    nome  valor
0  Selic  12.25
1    CDI  12.15
2   IPCA   4.82

In [18]:
bank.head()

,ispb,name,code,fullName
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.
2,00038121,Selic,NaN,Banco Central do Brasil - Selic
3,00038166,Bacen,NaN,Banco Central do Brasil
4,00122327,SANTINVEST S.A. - CFI,539.0,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV..."

In [19]:
pix.head()

,ispb,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,2020-11-03T09:30:00.000Z
3,00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,2020-11-03T09:30:00.000Z
4,00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,2020-11-03T09:30:00.000Z

In [114]:
Bank_pix = pd.merge(bank, pix, on="ispb",how="left")
Bank_pix.head()

,ispb,name,code,fullName,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00038121,Selic,NaN,Banco Central do Brasil - Selic,NaN,NaN,NaN,NaN,NaN
3,00038166,Bacen,NaN,Banco Central do Brasil,NaN,NaN,NaN,NaN,NaN
4,00122327,SANTINVEST S.A. - CFI,539.0,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV...",NaN,NaN,NaN,NaN,NaN

In [115]:
#Ajuste os nomes das colunas e linhas. 
Bank_pix = pd.DataFrame(Bank_pix)
Bank_pix = Bank_pix.rename(columns= 
                            {"name":"Nome",
                             "fullName":"Nome Completo",
                             "code":"Código",
                             "modalidade_participacao":"Modalidade de Participação",
                             "tipo_participacao":"Tipo de Participação",
                             "inicio_operacao":"Início da Operação"
                             })
Bank_pix = Bank_pix.drop(["nome","nome_reduzido"], axis =1)
Bank_pix

,ispb,Nome,Código,Nome Completo,Modalidade de Participação,Tipo de Participação,Início da Operação
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00038121,Selic,NaN,Banco Central do Brasil - Selic,NaN,NaN,NaN
3,00038166,Bacen,NaN,Banco Central do Brasil,NaN,NaN,NaN
4,00122327,SANTINVEST S.A. - CFI,539.0,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV...",NaN,NaN,NaN
...,...,...,...,...,...,...,...
354,92875780,WARREN CVMC LTDA,371.0,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,NaN,NaN,NaN
355,92894922,BANCO ORIGINAL,212.0,Banco Original S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
356,94968518,EFX CC LTDA.,289.0,EFX CORRETORA DE CÂMBIO LTDA.,NaN,NaN,NaN
357,,NaN,NaN,NaN,NaN,NaN,NaN
358,,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
#Ajuste de missing values

Bank_pix.dropna()

,ispb,Nome,Código,Nome Completo,Modalidade de Participação,Tipo de Participação,Início da Operação
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
5,00204963,CCR SEARA,430.0,COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA,PDCT,DRCT,2022-02-11T13:00:00.000Z
7,00315557,CONF NAC COOP CENTRAIS UNICRED,136.0,CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAI...,PDCT,DRCT,2020-11-03T09:30:00.000Z
8,00329598,ÍNDIGO INVESTIMENTOS DTVM LTDA.,407.0,ÍNDIGO INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS ...,PDCT,DRCT,2022-11-08T13:00:00.000Z
...,...,...,...,...,...,...,...
345,81723108,CREDICOAMO,10.0,CREDICOAMO CREDITO RURAL COOPERATIVA,PDCT,DRCT,2020-11-03T09:30:00.000Z
349,90400888,BCO SANTANDER (BRASIL) S.A.,33.0,BANCO SANTANDER (BRASIL) S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
351,92702067,BCO DO ESTADO DO RS S.A.,41.0,Banco do Estado do Rio Grande do Sul S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
353,92874270,BCO DIGIMAIS S.A.,654.0,BANCO DIGIMAIS S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
355,92894922,BANCO ORIGINAL,212.0,Banco Original S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z

In [118]:
#Tratamento de colunas string.

from datetime import datetime

Bank_pix ["Início da Operação"]=pd.to_datetime(Bank_pix["Início da Operação"]).dt.year
Bank_pix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ispb                        359 non-null    object
 1   Nome                        357 non-null    object
 2   Código                      348 non-null    float64
 3   Nome Completo               357 non-null    object
 4   Modalidade de Participação  150 non-null    object
 5   Tipo de Participação        150 non-null    object
 6   Início da Operação          150 non-null    float64
dtypes: float64(2), object(5)
memory usage: 19.8+ KB

In [125]:
modalidade = Bank_pix.groupby("Modalidade de Participação").count()
modalidade

,ispb,Nome,Código,Nome Completo,Tipo de Participação,Início da Operação
Modalidade de Participação,,,,,,
GOVE,1,1,0,1,1,1
LESP,4,4,4,4,4,4
PDCT,145,145,145,145,145,145

In [127]:
participacao = Bank_pix.groupby("Tipo de Participação").count()
participacao

,ispb,Nome,Código,Nome Completo,Modalidade de Participação,Início da Operação
Tipo de Participação,,,,,,
DRCT,147,147,146,147,147,147
IDRT,3,3,3,3,3,3

In [129]:
ano = Bank_pix.groupby("Início da Operação").count()
ano

,ispb,Nome,Código,Nome Completo,Modalidade de Participação,Tipo de Participação
Início da Operação,,,,,,
2020.0,83,83,82,83,83,83
2021.0,20,20,20,20,20,20
2022.0,19,19,19,19,19,19
2023.0,28,28,28,28,28,28

In [133]:
#Filtros de linhas e colunas, se necessário. 

bank_pix_filtro = Bank_pix[Bank_pix["Início da Operação"]>2022]
bank_pix_filtro

,ispb,Nome,Código,Nome Completo,Modalidade de Participação,Tipo de Participação,Início da Operação
16,00714671,EWALLY IP S.A.,534.0,EWALLY INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023.0
20,00997185,BCO B3 S.A.,96.0,Banco B3 S.A.,PDCT,DRCT,2023.0
62,04814563,BCO AFINZ S.A. - BM,299.0,BANCO AFINZ S.A. - BANCO MÚLTIPLO,PDCT,DRCT,2023.0
70,05351887,ZEMA CFI S/A,359.0,"ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A",PDCT,DRCT,2023.0
99,09210106,SOCRED SA - SCMEPP,183.0,SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMP...,PDCT,DRCT,2023.0
104,09516419,PICPAY BANK - BANCO MÚLTIPLO S.A,79.0,PICPAY BANK - BANCO MÚLTIPLO S.A,PDCT,DRCT,2023.0
120,11703662,TRAVELEX BANCO DE CÂMBIO S.A.,95.0,Travelex Banco de Câmbio S.A.,PDCT,DRCT,2023.0
122,11760553,GAZINCRED S.A. SCFI,478.0,"GAZINCRED S.A. SOCIEDADE DE CRÉDITO, FINANCIAM...",PDCT,DRCT,2023.0
134,13720915,BCO WESTERN UNION,119.0,Banco Western Union do Brasil S.A.,PDCT,DRCT,2023.0
136,13935893,CELCOIN IP S.A.,509.0,CELCOIN INSTITUICAO DE PAGAMENTO S.A.,PDCT,DRCT,2023.0
147,16695922,ID CTVM,439.0,ID CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS ...,PDCT,DRCT,2023.0
150,17079937,PINBANK IP,529.0,PINBANK BRASIL INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023.0
166,20855875,NEON PAGAMENTOS S.A. IP,536.0,NEON PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO,PDCT,DRCT,2023.0
169,22610500,VORTX DTVM LTDA.,310.0,VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...,PDCT,DRCT,2023.0
176,27214112,AL5 S.A. CFI,349.0,"AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO",PDCT,IDRT,2023.0
191,30980539,U4C INSTITUIÇÃO DE PAGAMENTO S.A.,546.0,U4C INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023.0
237,37715993,ACCREDITO SCD S.A.,406.0,ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
238,37880206,CORA SCD S.A.,403.0,CORA SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
242,39343350,CC LAR CREDI,421.0,LAR COOPERATIVA DE CRÉDITO - LAR CREDI,PDCT,DRCT,2023.0
245,39587424,UY3 SCD S/A,457.0,UY3 SOCIEDADE DE CRÉDITO DIRETO S/A,PDCT,IDRT,2023.0
248,39676772,CREDIFIT SCD S.A.,452.0,CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
251,40083667,CAPITAL CONSIG SCD S.A.,465.0,CAPITAL CONSIG SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
254,40475846,J17 - SCD S/A,451.0,J17 - SOCIEDADE DE CRÉDITO DIRETO S/A,PDCT,DRCT,2023.0
263,43599047,SUPERLÓGICA SCD S.A.,481.0,SUPERLÓGICA SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
269,44683140,MAGNUM SCD,511.0,MAGNUM SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
273,45756448,MICROCASH SCMEPP LTDA.,537.0,MICROCASH SOCIEDADE DE CRÉDITO AO MICROEMPREEN...,PDCT,DRCT,2023.0
318,62073200,BOFA MERRILL LYNCH BM S.A.,755.0,Bank of America Merrill Lynch Banco Múltiplo S.A.,PDCT,DRCT,2023.0
336,74828799,NOVO BCO CONTINENTAL S.A. - BM,753.0,Novo Banco Continental S.A. - Banco Múltiplo,PDCT,DRCT,2023.0

In [120]:
#Tratamento do tipo das variáveis.

bank_pix_filtro["Código"]=bank_pix_filtro["Código"].astype(int)
bank_pix_filtro

/var/folders/tw/07hgbxjx4k59hhm3dntqj1_80000gn/T/ipykernel_3077/838279261.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bank_pix_filtro["Código"]=bank_pix_filtro["Código"].astype(int)

,ispb,Nome,Código,Nome Completo,Modalidade de Participação,Tipo de Participação,Início da Operação
16,00714671,EWALLY IP S.A.,534,EWALLY INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023.0
20,00997185,BCO B3 S.A.,96,Banco B3 S.A.,PDCT,DRCT,2023.0
62,04814563,BCO AFINZ S.A. - BM,299,BANCO AFINZ S.A. - BANCO MÚLTIPLO,PDCT,DRCT,2023.0
70,05351887,ZEMA CFI S/A,359,"ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A",PDCT,DRCT,2023.0
99,09210106,SOCRED SA - SCMEPP,183,SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMP...,PDCT,DRCT,2023.0
104,09516419,PICPAY BANK - BANCO MÚLTIPLO S.A,79,PICPAY BANK - BANCO MÚLTIPLO S.A,PDCT,DRCT,2023.0
120,11703662,TRAVELEX BANCO DE CÂMBIO S.A.,95,Travelex Banco de Câmbio S.A.,PDCT,DRCT,2023.0
122,11760553,GAZINCRED S.A. SCFI,478,"GAZINCRED S.A. SOCIEDADE DE CRÉDITO, FINANCIAM...",PDCT,DRCT,2023.0
134,13720915,BCO WESTERN UNION,119,Banco Western Union do Brasil S.A.,PDCT,DRCT,2023.0
136,13935893,CELCOIN IP S.A.,509,CELCOIN INSTITUICAO DE PAGAMENTO S.A.,PDCT,DRCT,2023.0
147,16695922,ID CTVM,439,ID CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS ...,PDCT,DRCT,2023.0
150,17079937,PINBANK IP,529,PINBANK BRASIL INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023.0
166,20855875,NEON PAGAMENTOS S.A. IP,536,NEON PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO,PDCT,DRCT,2023.0
169,22610500,VORTX DTVM LTDA.,310,VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...,PDCT,DRCT,2023.0
176,27214112,AL5 S.A. CFI,349,"AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO",PDCT,IDRT,2023.0
191,30980539,U4C INSTITUIÇÃO DE PAGAMENTO S.A.,546,U4C INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023.0
237,37715993,ACCREDITO SCD S.A.,406,ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
238,37880206,CORA SCD S.A.,403,CORA SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
242,39343350,CC LAR CREDI,421,LAR COOPERATIVA DE CRÉDITO - LAR CREDI,PDCT,DRCT,2023.0
245,39587424,UY3 SCD S/A,457,UY3 SOCIEDADE DE CRÉDITO DIRETO S/A,PDCT,IDRT,2023.0
248,39676772,CREDIFIT SCD S.A.,452,CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
251,40083667,CAPITAL CONSIG SCD S.A.,465,CAPITAL CONSIG SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
254,40475846,J17 - SCD S/A,451,J17 - SOCIEDADE DE CRÉDITO DIRETO S/A,PDCT,DRCT,2023.0
263,43599047,SUPERLÓGICA SCD S.A.,481,SUPERLÓGICA SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
269,44683140,MAGNUM SCD,511,MAGNUM SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023.0
273,45756448,MICROCASH SCMEPP LTDA.,537,MICROCASH SOCIEDADE DE CRÉDITO AO MICROEMPREEN...,PDCT,DRCT,2023.0
318,62073200,BOFA MERRILL LYNCH BM S.A.,755,Bank of America Merrill Lynch Banco Múltiplo S.A.,PDCT,DRCT,2023.0
336,74828799,NOVO BCO CONTINENTAL S.A. - BM,753,Novo Banco Continental S.A. - Banco Múltiplo,PDCT,DRCT,2023.0

In [121]:
bank_pix_filtro["Início da Operação"]=bank_pix_filtro["Início da Operação"].astype(int)
bank_pix_filtro

/var/folders/tw/07hgbxjx4k59hhm3dntqj1_80000gn/T/ipykernel_3077/798350856.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bank_pix_filtro["Início da Operação"]=bank_pix_filtro["Início da Operação"].astype(int)

,ispb,Nome,Código,Nome Completo,Modalidade de Participação,Tipo de Participação,Início da Operação
16,00714671,EWALLY IP S.A.,534,EWALLY INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023
20,00997185,BCO B3 S.A.,96,Banco B3 S.A.,PDCT,DRCT,2023
62,04814563,BCO AFINZ S.A. - BM,299,BANCO AFINZ S.A. - BANCO MÚLTIPLO,PDCT,DRCT,2023
70,05351887,ZEMA CFI S/A,359,"ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A",PDCT,DRCT,2023
99,09210106,SOCRED SA - SCMEPP,183,SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMP...,PDCT,DRCT,2023
104,09516419,PICPAY BANK - BANCO MÚLTIPLO S.A,79,PICPAY BANK - BANCO MÚLTIPLO S.A,PDCT,DRCT,2023
120,11703662,TRAVELEX BANCO DE CÂMBIO S.A.,95,Travelex Banco de Câmbio S.A.,PDCT,DRCT,2023
122,11760553,GAZINCRED S.A. SCFI,478,"GAZINCRED S.A. SOCIEDADE DE CRÉDITO, FINANCIAM...",PDCT,DRCT,2023
134,13720915,BCO WESTERN UNION,119,Banco Western Union do Brasil S.A.,PDCT,DRCT,2023
136,13935893,CELCOIN IP S.A.,509,CELCOIN INSTITUICAO DE PAGAMENTO S.A.,PDCT,DRCT,2023
147,16695922,ID CTVM,439,ID CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS ...,PDCT,DRCT,2023
150,17079937,PINBANK IP,529,PINBANK BRASIL INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023
166,20855875,NEON PAGAMENTOS S.A. IP,536,NEON PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO,PDCT,DRCT,2023
169,22610500,VORTX DTVM LTDA.,310,VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...,PDCT,DRCT,2023
176,27214112,AL5 S.A. CFI,349,"AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO",PDCT,IDRT,2023
191,30980539,U4C INSTITUIÇÃO DE PAGAMENTO S.A.,546,U4C INSTITUIÇÃO DE PAGAMENTO S.A.,PDCT,DRCT,2023
237,37715993,ACCREDITO SCD S.A.,406,ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023
238,37880206,CORA SCD S.A.,403,CORA SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023
242,39343350,CC LAR CREDI,421,LAR COOPERATIVA DE CRÉDITO - LAR CREDI,PDCT,DRCT,2023
245,39587424,UY3 SCD S/A,457,UY3 SOCIEDADE DE CRÉDITO DIRETO S/A,PDCT,IDRT,2023
248,39676772,CREDIFIT SCD S.A.,452,CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023
251,40083667,CAPITAL CONSIG SCD S.A.,465,CAPITAL CONSIG SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023
254,40475846,J17 - SCD S/A,451,J17 - SOCIEDADE DE CRÉDITO DIRETO S/A,PDCT,DRCT,2023
263,43599047,SUPERLÓGICA SCD S.A.,481,SUPERLÓGICA SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023
269,44683140,MAGNUM SCD,511,MAGNUM SOCIEDADE DE CRÉDITO DIRETO S.A.,PDCT,DRCT,2023
273,45756448,MICROCASH SCMEPP LTDA.,537,MICROCASH SOCIEDADE DE CRÉDITO AO MICROEMPREEN...,PDCT,DRCT,2023
318,62073200,BOFA MERRILL LYNCH BM S.A.,755,Bank of America Merrill Lynch Banco Múltiplo S.A.,PDCT,DRCT,2023
336,74828799,NOVO BCO CONTINENTAL S.A. - BM,753,Novo Banco Continental S.A. - Banco Múltiplo,PDCT,DRCT,2023

In [134]:
#unstack e/ou stack.
Bank_pix_unstack = bank_pix_filtro.unstack()
Bank_pix_unstack

ispb                16     00714671
                    20     00997185
                    62     04814563
                    70     05351887
                    99     09210106
                             ...
Início da Operação  263      2023.0
                    269      2023.0
                    273      2023.0
                    318      2023.0
                    336      2023.0
Length: 196, dtype: object