In [1]:
%pip install requests

Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (2023.11.17)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [20]:
import requests
import pandas as pd

In [30]:
from plyer import notification
from datetime import datetime

def alerta(code,tabela):
    
    HTTPcode = {200: "Sucesso", 201:"Created", 203:"Non Authoritative information", 204:"No Content", 
            400:"Bad request", 401: "Unauthorized", 403: "Forbidden", 404: "Not Found", 409: "Conflict",
            500: "Internal Server Error", 501: "Not Implemented", 502: "Bad Gateway", 503: "Service Unavailable", 504: "Gateway Timeout", 599: "Network timeout"
            }
    mensagem = HTTPcode.get(code)
    data = str(datetime.now()) 
    
    notification.notify(
        title= f"Código{code}",
        message = f"{mensagem} ao carregar {tabela}\n {data}",
        timeout=10
    )

In [29]:
#Escolher uma API da lista disponibel

url = "https://brasilapi.com.br/"

#Tabela 1

url1 = "https://brasilapi.com.br/api/banks/v1"
tabela1 = requests.get(url1)
code1 =tabela1.status_code

if code1 ==200: #code 200 é o código de sucesso
    data_json1 = tabela1.json() #se for sucesso, converte o conteúdo da resposta da solicitação HTTP (em formato JSON) para um objeto Python
else:
    alerta(code1,"Bank")

bank = pd.DataFrame(data_json1)
bank.head()

,ispb,name,code,fullName
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.
2,00038121,Selic,NaN,Banco Central do Brasil - Selic
3,00038166,Bacen,NaN,Banco Central do Brasil
4,00122327,SANTINVEST S.A. - CFI,539.0,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV..."

In [32]:
#Tabela 2
url2 = "https://brasilapi.com.br/api/pix/v1/participants"
tabela2 = requests.get(url2)
code2 =tabela2.status_code

if code2==200: #code 200 é o código de sucesso
    data_json2 = tabela2.json() #se for sucesso, converte o conteúdo da resposta da solicitação HTTP (em formato JSON) para um objeto Python
else:
   alerta(code2,"pix")

pix = pd.DataFrame(data_json2)
pix.head()

,ispb,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,2020-11-03T09:30:00.000Z
3,00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,2020-11-03T09:30:00.000Z
4,00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,2020-11-03T09:30:00.000Z

In [31]:
#Tabela 3 
url3 = "https://brasilapi.com.br/api/taxas/v1"
tabela3 = requests.get(url3)
code3 = tabela3.status_code

if code3 ==200: #code 200 é o código de sucesso
    data_json3 = tabela3.json() #se for sucesso, converte o conteúdo da resposta da solicitação HTTP (em formato JSON) para um objeto Python
else:
    alerta(code3,"Taxas")

tax = pd.DataFrame(data_json3) 
tax

    nome  valor
0  Selic  12.25
1    CDI  12.15
2   IPCA   4.82